---

- name: "Create mountpoint"
  file:
    path: "{{ base_dir }}"
    state: "directory"
    recurse: "yes"
    mode: 777
    owner: "root"
    group: "root"

- name: "Ensure NFS utilities  are installed."
  yum:
    name: "{{ item }}"
    state: "installed"
    update_cache: "yes"
  with_items:
    - nfs-utils

- debug:
    msg: "Mirror IP: {{ hostvars['mirror-01']['ansible_all_ipv4_addresses'][0] }}"

# - name: set mountpoints
#   mount:
#     name: "{{ base_dir }}"
#     src: "{{ hostvars['mirror-01']['ansible_all_ipv4_addresses'][0] }}:{{ base_dir }}"
#     fstype: "nfs"
#     opts: "defaults,nobootwait"
#     state: "mounted"

- name: "Raw mount"
  shell: "mount -v -t nfs -o ro {{ hostvars['mirror-01']['ansible_all_ipv4_addresses'][0] }}:/srv/mirrors/  /srv/mirrors/"

- name: "Remove old repo confih"
  file:
    path: "/etc/yum.repos.d/*"
    state: absent

- name: "Add repository"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }}"
    baseurl: "file:/{{ item.base_dir }}{{ item.mirror_dir }}/$releasever/$basearch/"
    gpgkey: "file:/{{ item.base_dir }}{{ item.mirror_key }}"
  with_items: "{{ mirrors }}"


- name: "Raw umount"
  shell: "umount  /srv/mirrors/"
